// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAlksiyv-9G5XJygDgv0Y5RJAyiEerWc4',
    appId: '1:373056874634:web:09104a611b6224cb15a573',
    messagingSenderId: '373056874634',
    projectId: 'littlejohn-b3d57',
    authDomain: 'littlejohn-b3d57.firebaseapp.com',
    storageBucket: 'littlejohn-b3d57.firebasestorage.app',
    measurementId: 'G-2GG8HS47PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82vbYNsHG4N39UZk4CRNPUu1zr-duV_Q',
    appId: '1:373056874634:android:340458cf4dcf2eae15a573',
    messagingSenderId: '373056874634',
    projectId: 'littlejohn-b3d57',
    storageBucket: 'littlejohn-b3d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZhVTTw7i96yvJQnjCZMisDDviBf6Lk-A',
    appId: '1:373056874634:ios:37d9d1e94ac14f6415a573',
    messagingSenderId: '373056874634',
    projectId: 'littlejohn-b3d57',
    storageBucket: 'littlejohn-b3d57.firebasestorage.app',
    androidClientId: '373056874634-5tu7u8kpdhub5f18hk2g1ad1gchjttrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZhVTTw7i96yvJQnjCZMisDDviBf6Lk-A',
    appId: '1:373056874634:ios:37d9d1e94ac14f6415a573',
    messagingSenderId: '373056874634',
    projectId: 'littlejohn-b3d57',
    storageBucket: 'littlejohn-b3d57.firebasestorage.app',
    androidClientId: '373056874634-5tu7u8kpdhub5f18hk2g1ad1gchjttrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAlksiyv-9G5XJygDgv0Y5RJAyiEerWc4',
    appId: '1:373056874634:web:67c2e717e62d8f9415a573',
    messagingSenderId: '373056874634',
    projectId: 'littlejohn-b3d57',
    authDomain: 'littlejohn-b3d57.firebaseapp.com',
    storageBucket: 'littlejohn-b3d57.firebasestorage.app',
    measurementId: 'G-9P5F4S382S',
  );
}
